[build]
  command = "node app.js"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/server.html"
  status = 200

[[redirects]]
  from = "/event/*"
  to = "/event_server.html"
  status = 200
  force = true